### PR TITLE
BL-684: Allow logging for Alma gem via configuration.

### PR DESCRIPTION
**Pull request by dkinzer**
Also allow debugging for Alma gem via configuration.

### CODE REVIEW

**Comment by sensei100** [comment]
@dkinzer Why do we have to change the way we use HTTParty?  Is it necessary to have the extra Net file? I'm mostly concerned about making big changes like that since other libraries use this gem.

**Comment by dkinzer** [comment]
@sensei100 because we use HTTParty directly instead of including it we cannot set default logging mechanisms.  I did try to update HTTParty directly but I get an error.

**Comment by dkinzer** [comment]
Not sure if this is any assurance or not, but none of the changes I made affected the current specs.  I just added new tests to cover the new behavior but all the old behavior is the same.

**Comment by sensei100** [comment]
@dkinzer Would it be possible to include httparty in each class and then get the logging behavior that we want?

**Comment by dkinzer** [comment]
It's possible but with a lot more code and a lot more chances to introduce a bug.

Steps:
1.  Add include httparty
2.  override .get method in each to match what we do with HTTParty.get
3.  for each of the of these new classes enable config logging and debugging at intialization.

**Comment by dkinzer** [comment]
There might be a bit more than what I mentioned to accommodate for both .post and .get.

**Comment by sensei100** [comment]
@dkinzer Okay. It sounds like the other method won't work, so we will keep this original solution.  I'm going to merge this and then we can see how we want to use the logs in librarysearch since that pulls in changes to the main branch.  Once we are comfortable with that integration, we can prepare a release.

**Review by sensei100 — APPROVED** [review]

**Pull request merged**
